
spring:
  datasource:
    url: jdbc:h2:mem:device
    username: sa
    password:
    driverClassName: org.h2.Driver

  hazelcast.config: classpath:hazelcast.yml

  h2:
    console:
      enabled: true
      path: /h2-console

