INSERT INTO DEVICE (ID, NAME,VERSION) VALUES ('device-001', 'USA',0);
INSERT INTO DEVICE (ID, NAME,VERSION) VALUES ('device-002', 'France',0);
INSERT INTO DEVICE (ID, NAME,VERSION) VALUES ('device-003', 'Brazil',0);
INSERT INTO DEVICE (ID, NAME,VERSION) VALUES ('device-004', 'Italy',0);
INSERT INTO DEVICE (ID, NAME,VERSION) VALUES ('device-005', 'Canada',0);